import { CONFIG } from "./config.js";
function ageRank(age){if(age==="elder")return 3;if(age==="mature")return 2;return 1;}
export function createGame(familyNames){const players=familyNames.map((familyName,index)=>({id:`family_${index+1}`,familyName,prestige:0,influence:6,maxInfluence:CONFIG.defaultMaxInfluence,knowledge:0,characters:{young:null,mature:null,elder:null},productionStakes:[],resourceStakes:[],wealthGeneratedThisGeneration:0}));return{generation:1,phase:"action_phase",city:{population:3,squalor:0,order:0,force:0,economicStrength:0,renown:0,religionArcane:0,militaryMercantile:0},players,productionSectors:[{id:"food",name:"Food",tier:1,totalDemandThisGeneration:1,demandThisGeneration:{population:1,institutions:0,external_markets:0}},{id:"textiles",name:"Textiles",tier:1,totalDemandThisGeneration:1,demandThisGeneration:{population:1,institutions:0,external_markets:0}},{id:"smithing",name:"Smithing",tier:1,totalDemandThisGeneration:1,demandThisGeneration:{population:1,institutions:0,external_markets:0}}],lands:CONFIG.initialLands.map(land=>({...land,capacityModifier:0,usedCapacityThisGeneration:0})),nextPlacementOrder:1};}
export function getPlayer(state,playerId){const player=state.players.find(p=>p.id===playerId);if(!player)throw new Error(`Unknown player: ${playerId}`);return player;}
export function getSector(state,sectorId){const sector=state.productionSectors.find(s=>s.id===sectorId);if(!sector)throw new Error(`Unknown sector: ${sectorId}`);return sector;}
export function getSectorStakeCapacity(state,sectorId){const sector=getSector(state,sectorId);return{young:sector.tier,mature:sector.tier,elder:sector.tier,total:sector.tier*3};}
export function getSectorStakeOccupancy(state,sectorId,excludedStakeId=null){const stakes=state.players.flatMap(p=>p.productionStakes).filter(s=>s.sectorId===sectorId&&s.id!==excludedStakeId);const occupancy={young:0,mature:0,elder:0,total:stakes.length};for(const stake of stakes)occupancy[stake.age]+=1;return occupancy;}
function addStakeObject(state,playerId,sectorId,age){const player=getPlayer(state,playerId);const stake={id:`stake_${state.nextPlacementOrder}`,ownerId:playerId,sectorId,age,placementOrder:state.nextPlacementOrder,servedThisGeneration:false,wealthProducedThisGeneration:0};state.nextPlacementOrder+=1;player.productionStakes.push(stake);return stake;}
export function placeProductionStake(state,playerId,sectorId){const player=getPlayer(state,playerId);const capacity=getSectorStakeCapacity(state,sectorId);const occupancy=getSectorStakeOccupancy(state,sectorId);if(occupancy.young>=capacity.young)throw new Error("No available Young Stake slot in this Production Sector.");if(player.influence<CONFIG.stakePlacementInfluenceCost)throw new Error("Not enough Influence to place Stake.");player.influence-=CONFIG.stakePlacementInfluenceCost;return addStakeObject(state,playerId,sectorId,"young");}
/* Diagnostic-only helpers below manipulate board state without charging resources. */
export function addProductionStakeForTesting(state,playerId,sectorId,age){if(!["young","mature","elder"].includes(age))throw new Error(`Invalid Stake age: ${age}`);const capacity=getSectorStakeCapacity(state,sectorId);const occupancy=getSectorStakeOccupancy(state,sectorId);if(occupancy[age]>=capacity[age])throw new Error(`No available ${age} Stake slot in this Production Sector.`);return addStakeObject(state,playerId,sectorId,age);}
export function findProductionStake(state,stakeId){for(const player of state.players){const stake=player.productionStakes.find(s=>s.id===stakeId);if(stake)return{player,stake};}throw new Error(`Unknown production Stake: ${stakeId}`);}
export function removeProductionStake(state,stakeId){const{player}=findProductionStake(state,stakeId);player.productionStakes=player.productionStakes.filter(s=>s.id!==stakeId);}
export function setProductionStakeOwner(state,stakeId,newOwnerId){const{player:oldPlayer,stake}=findProductionStake(state,stakeId);const newPlayer=getPlayer(state,newOwnerId);if(oldPlayer.id===newPlayer.id)return stake;oldPlayer.productionStakes=oldPlayer.productionStakes.filter(s=>s.id!==stakeId);stake.ownerId=newOwnerId;newPlayer.productionStakes.push(stake);return stake;}
export function setProductionStakeAge(state,stakeId,newAge){if(!["young","mature","elder"].includes(newAge))throw new Error(`Invalid Stake age: ${newAge}`);const{stake}=findProductionStake(state,stakeId);if(stake.age===newAge)return stake;const capacity=getSectorStakeCapacity(state,stake.sectorId);const occupancy=getSectorStakeOccupancy(state,stake.sectorId,stakeId);if(occupancy[newAge]>=capacity[newAge])throw new Error(`No available ${newAge} Stake slot in this Production Sector.`);stake.age=newAge;stake.servedThisGeneration=false;stake.wealthProducedThisGeneration=0;return stake;}
export function setResourceStakeOwner(state,landId,newOwnerId){if(!state.lands.some(land=>land.id===landId))throw new Error(`Unknown land: ${landId}`);for(const player of state.players)player.resourceStakes=player.resourceStakes.filter(s=>s.landId!==landId);if(!newOwnerId)return;const player=getPlayer(state,newOwnerId);player.resourceStakes.push({id:`${newOwnerId}-${landId}`,ownerId:newOwnerId,landId});}
export function setLandBaseCapacity(state,landId,value){const land=state.lands.find(l=>l.id===landId);if(!land)throw new Error(`Unknown land: ${landId}`);land.baseCapacity=Math.max(0,Math.floor(Number(value)||0));land.usedCapacityThisGeneration=0;}
export function setLandCapacityModifier(state,landId,value){const land=state.lands.find(l=>l.id===landId);if(!land)throw new Error(`Unknown land: ${landId}`);land.capacityModifier=Math.floor(Number(value)||0);land.usedCapacityThisGeneration=0;}
export function developSector(state,playerId,sectorId){const player=getPlayer(state,playerId);const sector=getSector(state,sectorId);const nextTier=sector.tier+1;if(nextTier>3)throw new Error("Prototype supports only three tiers.");const config=CONFIG.sectorDevelopment[nextTier];if(player.influence<config.influenceCost)throw new Error("Not enough Influence to develop Sector.");player.influence-=config.influenceCost;player.prestige+=config.prestigeReward;sector.tier=nextTier;}
export function resolveServedStakes(state,sectorId,demand){const stakes=state.players.flatMap(p=>p.productionStakes).filter(s=>s.sectorId===sectorId);for(const stake of stakes){stake.servedThisGeneration=false;stake.wealthProducedThisGeneration=0;}const sorted=[...stakes].sort((a,b)=>{const ageDifference=ageRank(b.age)-ageRank(a.age);if(ageDifference!==0)return ageDifference;return a.placementOrder-b.placementOrder;});const served=sorted.slice(0,Math.max(0,demand));for(const stake of served){stake.servedThisGeneration=true;stake.wealthProducedThisGeneration=1;}for(const player of state.players)player.wealthGeneratedThisGeneration=player.productionStakes.reduce((sum,stake)=>sum+stake.wealthProducedThisGeneration,0);return served;}
export function erodeInfluence(state){for(const player of state.players)player.influence=Math.max(0,player.influence-CONFIG.influenceErosion);}
export function ageProductionStakes(state){for(const player of state.players){player.productionStakes=player.productionStakes.filter(stake=>stake.age!=="elder").map(stake=>({...stake,age:stake.age==="young"?"mature":"elder",servedThisGeneration:false,wealthProducedThisGeneration:0}));}}
export function advanceGeneration(state){erodeInfluence(state);ageProductionStakes(state);state.generation+=1;state.phase="action_phase";}
