import * as base from "./v089-engine.js?real=0.8.9-v102";

export * from "./v089-engine.js?real=0.8.9-v102";

const SIMULATION_RENOWN_LONGEVITY_INTERVAL = 5;
const EXTERNAL_DEMAND_RENOWN_DIVISOR = 4;

// v0.10.2: automatic +5 Influence income remains removed. Influence is now
// generated by persistent Institution Agents after the normal −2 erosion.
// Renown is structurally recalculated from visible board state. The +1 every
// 5 completed Generations is simulation-only scaffolding until Intrigue cards
// provide their intended permanent Renown contribution.
export const V084_CONFIG = {
  ...base.V084_CONFIG,
  influence: {
    ...base.V084_CONFIG.influence,
    grossIncome: 0,
  },
  renown: {
    ...base.V084_CONFIG.renown,
    gainEveryGenerations: SIMULATION_RENOWN_LONGEVITY_INTERVAL,
    gainAmount: 1,
    // Legacy wrappers still read this field. Structural Renown has no
    // Population-based cap, so make the legacy cap effectively unreachable.
    capPerPopulation: Number.MAX_SAFE_INTEGER,
    populationDivisor: 2,
    productionTierContribution: 1,
    institutionTierContribution: 1,
    externalDemandDivisor: EXTERNAL_DEMAND_RENOWN_DIVISOR,
    simulationLongevityEveryGenerations: SIMULATION_RENOWN_LONGEVITY_INTERVAL,
  },
};

const DEFAULT_IMPERIAL_DEMAND_THRESHOLD = 3;

function clampInt(value, minimum = 0) {
  return Math.max(minimum, Math.floor(Number(value) || 0));
}

function completedGenerations(state) {
  return Math.max(0, clampInt(state?.generation ?? 1, 1) - 1);
}

function productionTierRenown(state) {
  return (state?.productionSectors ?? []).reduce((sum, sector) => {
    // Raw Food is not a Production Sector in the current design. Keep the
    // legacy food object out of the structural Renown calculation.
    if (sector?.id === "food") return sum;
    return sum + Math.max(0, clampInt(sector?.tier ?? 1, 1) - 1);
  }, 0);
}

function institutionTierRenown(state) {
  return (state?.institutions ?? []).reduce(
    (sum, institution) => sum + Math.max(0, clampInt(institution?.tier ?? 1, 1) - 1),
    0,
  );
}

export function calculateRenownBreakdown(state) {
  const population = Math.max(1, clampInt(state?.city?.population ?? 1, 1));
  const populationRenown = Math.floor(population / V084_CONFIG.renown.populationDivisor);
  const productionRenown = productionTierRenown(state);
  const institutionRenown = institutionTierRenown(state);
  const completed = completedGenerations(state);
  const simulationLongevityRenown = Math.floor(
    completed / V084_CONFIG.renown.simulationLongevityEveryGenerations,
  );
  const total = populationRenown
    + productionRenown
    + institutionRenown
    + simulationLongevityRenown;

  return {
    population,
    populationRenown,
    productionRenown,
    institutionRenown,
    simulationLongevityRenown,
    completedGenerations: completed,
    total,
    simulationOnlyLongevity: true,
  };
}

export function recalculateRenown(state) {
  const breakdown = calculateRenownBreakdown(state);
  if (state?.city) {
    state.city.renown = breakdown.total;
    state.city.renownBreakdown = { ...breakdown };
  }
  return breakdown;
}

function externalDemandFromRenown(renown) {
  return Math.floor(clampInt(renown) / EXTERNAL_DEMAND_RENOWN_DIVISOR);
}

function legacyRenownProxy(renown) {
  // The legacy economy preview internally computes ceil(Renown / 2). Feed it
  // an equivalent temporary Renown so its report resolves to floor(real / 4)
  // without modifying the archived engine.
  const desiredDemand = externalDemandFromRenown(renown);
  return desiredDemand <= 0 ? 0 : desiredDemand * 2 - 1;
}

function applyExternalDemand(state) {
  const demand = externalDemandFromRenown(state?.city?.renown ?? 0);
  for (const sector of state?.productionSectors ?? []) {
    sector.demandThisGeneration ??= {};
    sector.demandThisGeneration.external_markets = demand;
  }
  return demand;
}

function interventionValue(state) {
  return clampInt(state?.city?.imperialIntervention, 0);
}

function demandThreshold(state) {
  return Math.max(1, clampInt(
    state?.city?.imperialDemandThreshold ?? DEFAULT_IMPERIAL_DEMAND_THRESHOLD,
    1,
  ));
}

function imperialDemandPerSector(state) {
  return Math.floor(interventionValue(state) / demandThreshold(state));
}

function guardImperialDemand(state) {
  for (const sector of state.productionSectors ?? []) {
    if (sector.id === "food") continue;
    const demand = sector.demandThisGeneration ?? {};
    Object.defineProperty(demand, "imperial", {
      enumerable: true,
      configurable: true,
      get() {
        return imperialDemandPerSector(state);
      },
      set() {
        // Ignore legacy fixed-baseline writes. Intervention/threshold are the
        // single source of truth for Imperial production demand in v0.10.2.
      },
    });
    sector.demandThisGeneration = demand;
  }
}

export function applyAutoDemand(state) {
  recalculateRenown(state);
  base.applyAutoDemand(state);
  guardImperialDemand(state);
  applyExternalDemand(state);
}

export function previewEconomy(state) {
  recalculateRenown(state);
  guardImperialDemand(state);

  const realRenown = state.city.renown;
  const proxyRenown = legacyRenownProxy(realRenown);
  state.city.renown = proxyRenown;

  try {
    return base.previewEconomy(state);
  } finally {
    state.city.renown = realRenown;
    guardImperialDemand(state);
    applyExternalDemand(state);
  }
}

export function projectedWealthCapacity(state, playerId) {
  return previewEconomy(state).familyWealth[playerId] ?? base.V084_CONFIG.familyBaseWealth;
}
